Hm2 all
robotE13/practice-on-JS pull request #1
Opened 2016-11-09 20:57 UTC by robotE13

Все части. Разложено по папкам.

2016-11-09 21:19 UTC, smelukov requested changes

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/01/index.js
> +        do{
решение этой задачи будет выглядеть гораздо проще, если применить `for` вместо `do..while`
здесь простой массив и перебирать его через `do..while` - это совсем экзотический вариант.

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/01/index.js
> +    return result;
здесь логика неверная.
по-хорошему, функция должна возвращать только один типа значения
если функция возвращает разные типы, в зависимости от входящих данных, то высока вероятность, что такая функция не сможет быть оптимизирована движком
плюс ко всему, это накладывает на разработчика, который будет пользоваться этой функцией, дополнительные обязательства по проверке возвращаемых значений
например нельзя будет проверить результат функции таким образом:
```javascript
if (isAllTypeOf( ... )) {
  ...
}
```
потому что неизвестно что вернула функция - true или текст ошибки

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/01/index.js
> +    if (source.length === 0)
не совсем корректная проверка.
например, если по ошибке передать в `source` какую-нибудь функцию, то она тоже будет иметь свойство `length`, в котором будет содержаться количество параметров этой функции

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/02/index.js
> +        do{
тот же комментарий по перебору обычного массива, что и выше

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/02/index.js
> +    return result;
тот же комментарий по поводу возврата разных типов данных, что и выше
более того, функция выбрасывает исключения и тут же их обрабатывает
то есть ты нагружаешь функцию дополнительными задачами

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/02/index.js
> +    if (source.length === 0)
тот же комментарий по поводу проверки размера массива

2016-11-09 21:19 UTC, smelukov commented on public_html/hm2/03/index.js
> +        return result;
то же самое, что и выше, по поводу возврата значений
если функция выбрасывает исключение, то и пусть себе выбрасывает
его(исключение) всегда можно обработать обернув в `try..catch` вызов самой функции

2016-11-10 10:12 UTC, robotE13 commented on public_html/hm2/01/index.js
> +        do{
Я переделал все в соответствии с замечаниями. 
Но по поводу цикла есть вот какие соображения. Просто я как до давным давно привык, использовать do...while, если в процессе выполнения возможно досрочное завершение цикла. Так нагляднее, по сравнению с for(), получается тот момент, что цикл может завершиться не только в случае достижения конца массива. Учили меня так давным давно в университете.

2016-11-10 16:01 UTC, smelukov requested changes

2016-11-10 16:01 UTC, smelukov commented on public_html/hm2/01/index.js
> +            result = false;
если хотя бы один элемент не прошел проверку, то можно просто сделать `return false`
тогда и от `&& result` в цикле можно избавиться

2016-11-10 16:01 UTC, smelukov commented on public_html/hm2/02/index.js
> +            result = true;
если хотя бы один элемент прошел проверку, то можно просто сделать `return true`
тогда и от `&& !result` в цикле можно избавиться

2016-11-15 20:05 UTC, merged