Домашняя работа #3 часть 2
robotE13/practice-on-JS pull request #3
Opened 2016-11-14 10:53 UTC by robotE13

2016-11-14 11:39 UTC, smelukov requested changes

2016-11-14 11:39 UTC, smelukov commented on public_html/hm3/02/index.js
> +    return (obj1 !== null && typeof obj1 === 'object') && (obj2 !== null && typeof obj2 === 'object');
можно сократить до
`return typeof obj1 == 'object'  && obj1 && typeof obj2 == 'object' && obj2;`

2016-11-14 11:39 UTC, smelukov commented on public_html/hm3/02/index.js
> +        if(iterator.length === 0)
зачем это условие?
проще сравнить `obj1` и `obj2` в самом начале работы функции

2016-11-14 11:39 UTC, smelukov commented on public_html/hm3/02/index.js
> +                if(!objectsEqual(obj1[index],obj2[index]))
очень странно здесь...
ты ведь уже вызывал `objectsEqual` с этими же аргументами
то есть если срабатывает первый `if` то этот `if` никогда не сработает

2016-11-15 15:38 UTC, robotE13 commented
Я по последнему комментарию обновление сделал, а вот по первым двум... похоже я лучше код перепишу. Получилось видимо запутанно и непонятно зачем эти проверки именно такие. Попробую пологичнее все в целом сделать.

2016-11-15 16:42 UTC, robotE13 commented on public_html/hm3/02/index.js
> +        if(iterator.length === 0)
Мне вот эта проверка нужна на случай если попал объект но без свойств в данном случае Date. Тогда для такого объекта я и вызываю valueOf и сравниваю их. Я просто не знаю как еще сравнить можно такие объекты.

2016-11-15 17:26 UTC, robotE13 commented on public_html/hm3/02/index.js
> +                if(!objectsEqual(obj1[index],obj2[index]))
Здесь я вызываю `objectsEqual`  и `objectsBoth` для перебираемых свойств. Делаю первую проверку чтобы не вызывать рекурсивно `objectsEqual` прямо для каждого элемента, а только для объектов или массивов, а остальные сравнивать обычным образом.
Код я переписал, убрав эту вложенность и с виду конечно красивее и понятнее стало. НО!!! Меня смущает что стек вызовов будет расти при каждой проверке одного отдельно взятого свойства, а не только если вложенное свойство - объект.

2016-11-15 19:56 UTC, smelukov requested changes

2016-11-15 19:56 UTC, smelukov commented on public_html/hm3/02/index.js
> +    if(!objectsBoth(variable1,variable2))
можно проще
```js
if (variable1 === variable2) {
  return true
}
```
даже `else` не нужен

2016-11-15 19:56 UTC, smelukov commented on public_html/hm3/02/index.js
> +        }else if(iterator.length === 0){// Мне вот эта проверка нужна на случай если попал объект но без свойств в данном случае Date
это очень странная проверка на `Date`
логичнее и понятнее - `if (variable1 instanceof Date && variable2 instanceof Date)`

2016-11-16 11:14 UTC, robotE13 commented on public_html/hm3/02/index.js
> +    if(!objectsBoth(variable1,variable2))
Да else убрал. Но сравнение через
```
if(!objectsBoth(variable1,variable2))
    {
        return variable1 === variable2;
```
Все равно оставил иначе null, если он только в одной переменной просочиться дальше. И там его дополнительно по коду отлавливать придется.

2016-11-17 19:48 UTC, smelukov requested changes

2016-11-17 19:48 UTC, smelukov commented on public_html/hm3/02/index.js
> +    if(variable1 instanceof Date || variable2 instanceof Date)//здесь именно || иначе Date и пустой Array не попадут вообще в сравнение и вернется true
должно быть именно && )
твой комментарий связан с тем, что ты изначально неправильно построил логику и порядок сравнений.

2016-11-19 12:03 UTC, robotE13 commented on public_html/hm3/02/index.js
> +    if(variable1 instanceof Date && variable2 instanceof Date)
Заменил здесь вот на такое вот сравнение. То есть проверяю одинакового ли класса (или как это правильно в JS назвать?) сравниваемые объекты. Если так совсем не правильно то я тогда в тупике насчет логики сравнения.
Пока она такая:
1. Отсекаются все НЕ объекты (неважно обе или одна только переменная НE Object) и дальше строгое сравнение между собой. То есть все простые типы, null, undefined проверены.
2. Дальше уже идут только сравнения объектов между собой.
2.1 Сравниваются классы объектов. И дальше уже остается только сравнение заведомо двух объектов одинакового класса (массив с массивом, объект с объектом и т д)
2.2. Сравниваем даты. Останутся только Array, и Object
2.3. У объектов одного и того же класса сравниваем кол-во свойств (для массивов кол-во элементов значит) и таким образом отброшены будут [1] === [1,2] Останутся уже гарантированно объекты с одинаковым кол-вом свойств.
2.4 ну и отсекаются те у кого уже значения свойств не совпадают. Причем поскольку по спискам ключей идем то для массивов будет логика соблюдена, когда должны быть !== [1,2] и [2,1]
3 Ну и если все проверки пройдены, значит объекты одного класса и все значения свойств совпали.

2016-11-19 12:08 UTC, robotE13 commented on public_html/hm3/02/index.js
> +    if(variable1 instanceof Date || variable2 instanceof Date)//здесь именно || иначе Date и пустой Array не попадут вообще в сравнение и вернется true
Добавил сравнение сначала. 
```
if(variable1.constructor().toString() !== variable2.constructor().toString())
{
     return false;
}
```
То есть проверяю одинакового ли класса (или как это правильно в JS назвать?) сравниваемые объекты. Если так совсем не правильно то я тогда в тупике насчет логики сравнения.
Пока она такая:
1. Отсекаются все НЕ объекты (неважно обе или одна только переменная НE Object) и дальше строгое сравнение между собой. То есть все простые типы, null, undefined проверены.
2. Дальше уже идут только сравнения объектов между собой.
2.1 Сравниваются классы объектов. И дальше уже остается только сравнение заведомо двух объектов одинакового класса (массив с массивом, объект с объектом и т д)
2.2. Сравниваем даты. Останутся только Array, и Object
2.3. У объектов одного и того же класса сравниваем кол-во свойств (для массивов кол-во элементов значит) и таким образом отброшены будут [1] === [1,2] Останутся уже гарантированно объекты с одинаковым кол-вом свойств.
2.4 ну и отсекаются те у кого уже значения свойств не совпадают. Причем поскольку по спискам ключей идем то для массивов будет логика соблюдена, когда должны быть !== [1,2] и [2,1]
3 Ну и если все проверки пройдены, значит объекты одного класса и все значения свойств совпали.``

2016-12-06 07:34 UTC, smelukov approved these changes

2016-12-06 09:26 UTC, merged