Домашняя работа #4 часть 1
robotE13/practice-on-JS pull request #4
Opened 2016-11-17 11:03 UTC by robotE13

2016-11-17 19:48 UTC, smelukov requested changes

2016-11-17 19:48 UTC, smelukov commented on public_html/hm4/01/index.js
> +    return container.insertBefore(element,container.firstElementChild);
а если первым элементом будет текстовый узел?

2016-11-17 21:24 UTC, robotE13 commented on public_html/hm4/01/index.js
> +        prepend(mainContainer,mainContainer.lastChild);
Здесь тоже поменял выбор перемещаемого в начало элемента на любой тип, чтобы порядок дочерних текстовых узлов и узлов-элементов сохранялся.

2016-11-17 21:27 UTC, robotE13 commented on public_html/hm4/01/index.js
> +        prepend(mainContainer,mainContainer.lastChild);
Здесь тоже поменял выбор перемещаемого в начало элемента на любой тип, чтобы порядок дочерних текстовых узлов и узлов-элементов сохранялся.

2016-12-06 07:33 UTC, smelukov approved these changes

2016-12-06 09:26 UTC, merged